apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

patches:
- path: route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 66c18fd5ea41876855be4d21184000709a86f2cf
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 66c18fd5ea41876855be4d21184000709a86f2cf
