apiVersion: v1
kind: ConfigMap
metadata:
  name: team-tracker-config
data:
  NODE_ENV: "production"
  API_PORT: "3001"
  JIRA_HOST: "https://redhat.atlassian.net"
  ADMIN_EMAILS: "acorvin@redhat.com,acorvin@cluster.local"
